# fly.toml app configuration file generated for fightingnerd on 2025-11-17T19:14:04+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fightingnerd'
primary_region = 'fra'

[build]

[env]
# Add any non-secret env vars here if needed

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "bot_config"
  destination = "/app/res"
