#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx8192M
kotlin.native.cacheKind=none

#Gradle
org.gradle.jvmargs=-Xmx8192M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

#App Version
app.version.name=0.2.0

# Bot Version
bot.version.name=12.1.1