package io.github.sophon.wiki.adapter.outbound.ktor.dustLoop

import io.github.sophon.wiki.adapter.outbound.ktor.CargoTable
import io.github.sophon.wiki.model.wiki.Game

internal object DustLoopTables {
    val characterTableByGame = mapOf(
        Game.GGST to CargoTable(name = "ggstCharacters", fieldList = ggstCharacterFieldList),
        Game.DBFZ to CargoTable(name = "dbfzCharacters", fieldList = dbfzCharacterFieldList),
        Game.GBVSR to CargoTable(name = "gbvsrCharacters", fieldList = gbvsrCharacterFieldList),
        Game.BBCF to CargoTable(name = "bbcfCharacters", fieldList = bbcfCharacterFieldList),
        Game.MTFS to CargoTable(name = "mtfsCharacters", fieldList = mtfsCharacterFieldList),
    )

    val moveTableByGame = mapOf(
        Game.GGST to CargoTable(name = "MoveData_GGST", fieldList = ggstMoveFieldList),
        Game.DBFZ to CargoTable(name = "MoveData_DBFZ", fieldList = dbfzMoveFieldList),
        Game.GBVSR to CargoTable(name = "MoveData_GBVSR", fieldList = gbvsrMoveFieldList),
        Game.BBCF to CargoTable(name = "MoveData_BBCF", fieldList = bbcfMoveFieldList),
        Game.MTFS to CargoTable(name = "MoveData_MTFS", fieldList = mtfsMoveFieldList),
    )
}


private val ggstCharacterFieldList = listOf(
    "name",
    "defense",
    "guts",
    "guardBalance",
    "prejump",
    "backdash",
    "backdashDuration",
    "backdashInvuln",
    "backdashAirborne",
    "backdashDistance",
    "forwarddash",
    "umo",
    "jump_duration",
    "high_jump_duration",
    "jump_height",
    "high_jump_height",
    "earliest_iad",
    "ad_duration",
    "abd_duration",
    "ad_distance",
    "abd_distance",
    "movement_tension",
    "jump_tension",
    "airdash_tension",
    "walk_speed",
    "back_walk_speed",
    "dash_initial_speed",
    "dash_acceleration",
    "dash_friction",
    "jump_gravity",
    "high_jump_gravity",
    "boost_attack",
    "boost_defense",
    "portrait",
    "icon",
    "nav_image",
)

private val dbfzCharacterFieldList = listOf(
    "name",
    "portrait",
    "icon",
    "kimod",
    "umo",
    "aliases",
)

private val gbvsrCharacterFieldList = listOf(
    "name",
    "health",
    "prejump",
    "backdash",
    "umo",
    "portrait",
    "icon",
    "walk_speed",
    "backwalk_speed",
    "dash_initial_speed",
    "dash_acceleration",
    "jump_height",
    "f_jump_distance",
    "b_jump_distance",
    "jump_gravity",
    "superjump_height",
    "f_superjump_distance",
    "b_superjump_distance",
    "superjump_gravity",
    "close_l_range",
    "close_m_range",
    "close_h_range",
)

private val bbcfCharacterFieldList = listOf(
    "name",
    "health",
    "prejump",
    "backdash",
    "forwarddash",
    "umo",
    "portrait",
    "icon",
)

private val mtfsCharacterFieldList = listOf(
    "name",
    "prejump",
    "backdash",
    "team",
    "umo",
    "portrait",
    "icon",
)

private val ggstMoveFieldList = listOf(
    "chara",
    "name",
    "input",
    "damage",
    "guard",
    "startup",
    "active",
    "recovery",
    "onBlock",
    "onHit",
    "level",
    "counter",
    "images",
    "hitboxes",
    "notes",
    "type",
    "riscGain",
    "riscLoss",
    "wallDamage",
    "inputTension",
    "chipRatio",
    "OTGType",
    "prorate",
    "invuln",
    "cancel",
    "caption",
    "hitboxCaption",
)

private val dbfzMoveFieldList = listOf(
    "chara",
    "name",
    "input",
    "damage",
    "guard",
    "startup",
    "active",
    "recovery",
    "onBlock",
    "attribute",
    "smash",
    "kigain",
    "invuln",
    "prorate",
    "level",
    "blockstun",
    "groundHit",
    "airHit",
    "images",
    "hitboxes",
    "type",
    "notes",
    "caption",
    "hitboxCaption",
)

private val gbvsrMoveFieldList = listOf(
    "chara",
    "name",
    "input",
    "damage",
    "guard",
    "startup",
    "active",
    "recovery",
    "onBlock",
    "onHit",
    "onCH",
    "meter",
    "level",
    "invuln",
    "cooldown",
    "cls",
    "images",
    "caption",
    "hitboxes",
    "hitboxCaption",
    "type",
    "notes",
)

private val bbcfMoveFieldList = listOf(
    "chara",
    "name",
    "input",
    "damage",
    "guard",
    "startup",
    "active",
    "recovery",
    "onBlock",
    "onODR",
    "attribute",
    "invuln",
    "cancel",
    "p1",
    "p2",
    "starter",
    "level",
    "blockstun",
    "groundHit",
    "airHit",
    "groundCH",
    "airCH",
    "blockstop",
    "hitstop",
    "CHstop",
    "cancelTiming",
    "images",
    "caption",
    "hitboxes",
    "hitboxCaption",
    "type",
    "notes",
)

private val mtfsMoveFieldList = listOf(
    "chara",
    "name",
    "input",
    "simpleInput",
    "damage",
    "guard",
    "startup",
    "active",
    "recovery",
    "onBlock",
    "onHit",
    "level",
    "type",
    "prorate",
    "invuln",
    "untechAmount",
    "meterGain",
    "hitboxCaption",
    "images",
    "hitboxes",
    "notes",
)
